//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Common.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.StockLevel1 = "\"-\"";
            this.StockLevel2 = "\"-\"";
            this.Pack = "\"\"";
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> SubcategoryID { get; set; }
        public string StockLevel1 { get; set; }
        public string StockLevel2 { get; set; }
        public string Pack { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
