//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Common.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Settings()
        {
            this.AskConfirmation = true;
            this.LoadImage = true;
        }
    
        public int ID { get; set; }
        public int UpdateInterval { get; set; }
        public bool AskConfirmation { get; set; }
        public bool LoadImage { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
