//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Common.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int TransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Quantity { get; set; }
        public decimal TotalCost { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
